server:
  port: 8080

logging:
  file:
    name: "log/main.log"
  level:
    com.toyu.simple.http.api: DEBUG

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/http_api_db"
    username: "root"
    password: "rootpass"
    driver-class-name: "com.mysql.cj.jdbc.Driver"
  sql:
    init:
      schema-locations: "classpath:sql"
